# Generated by Django 5.2.12 on 2026-03-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('passport_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('passport_expiry', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('traveler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='traveler_service.traveler')),
                ('reason', models.TextField()),
                ('flag_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('border_location', models.CharField(max_length=100)),
                ('officer_id', models.CharField(max_length=50)),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='traveler_service.traveler')),
            ],
        ),
        migrations.CreateModel(
            name='VisaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='traveler_service.traveler')),
            ],
        ),
    ]
